name: ImageBuilder
# Run this workflow every time a new commit pushed to your repository
on: push

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Troubleshooting
        run: |
            curl -sSL -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | \
            jq "{ jwt: .value, role: \"$VAULT_ROLE\" }" > ./token.json
            echo $ACTIONS_ID_TOKEN_REQUEST_URL
            echo $ACTIONS_ID_TOKEN_REQUEST_TOKEN
            echo 'GitHub Actions Token Claims'
            cat ./token.json | jq -r '.jwt | split(".") | .[1] | @base64d' | jq
      - name: Import Secrets
        uses: hashicorp/vault-action@v2
        with:
          url: http://127.0.0.1:8200
          tlsSkipVerify: true
          method: jwt
          role: myproject-production
#          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/ci app_secret
      - name: Build Docker Image
        run: docker build . --file Dockerfile --build-arg app_secret="${{ env.APP_SECRET }}" -t    vault-action-exampleapp
